Develop
gangadhar5613/js_closure pull request #1
Opened 2020-10-12 15:55 UTC by gangadhar5613

2020-10-13 06:02 UTC, nnnkit requested changes
Make the required changes and push again and merge it

2020-10-13 06:02 UTC, nnnkit commented on 2-higher-order-functions/eloquent/exercise.js
> +}
Don't write code in one line! Indent properly.

2020-10-13 06:02 UTC, nnnkit commented on 2-higher-order-functions/eloquent/exercise.js
> +
What is n? Define `n`

2020-10-13 06:02 UTC, nnnkit commented on practice/closure.md
> +  }
Fin the logic error!

2020-10-13 06:02 UTC, nnnkit commented on practice/closure.md
> +  }
Write code that human understands.

2020-10-13 06:02 UTC, nnnkit commented on practice/closure.md
> +  }
Change random to `randomCard`

2020-10-13 06:02 UTC, nnnkit commented on practice/hoisting.md
> +// reference error;
Uncaught ReferenceError: Cannot access 'animal' before initialization

2020-10-13 06:02 UTC, nnnkit commented on practice/hoisting.md
>  ```
DO it again!

2020-10-14 11:29 UTC, closed without merging

2020-10-14 11:38 UTC, gangadhar5613 reviewed
Accept the changes and completed changed and merged it to main branch